name: python workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: python hello.py
  build:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_artifact
          path: .
          
